## template: jinja
#cloud-config

{% if not pro_token %}
apt:
  sources:
    ros2:
      source: "deb [arch={{ architecture }}] http://packages.ros.org/ros2/ubuntu {{ distro_release }} main"
      keyid: C1CF 6E31 E6BA DE88 68B1 72B4 F42E D6FB AB17 C654
{% else %}
ubuntu_pro:
  enable: [esm-apps, esm-infra, ros]
  token: "{{ pro_token }}"
snap:
  commands:
  - snap install ros-esm-dependencies-diff-generator --beta
{% endif %}
package_update: true
package_upgrade: true

packages:
  - build-essential
  - cmake
  - curl
  - git
  - lsb-release
  - python3
  - python3-colcon-common-extensions
  - python3-pip
  - python3-venv

write_files:
  - content: |
      if [ -f /opt/ros/*/setup.bash ]; then
        . /opt/ros/*/setup.bash
      fi
      if [ -f /root/ws_underlay/install/setup.bash ]; then
        . /root/ws_underlay/install/setup.bash
      fi
      if [ -f /root/.venv/bin/activate ]; then
        . /root/.venv/bin/activate
      fi
      cd /root/ws
    path: /root/.bashrc
    append: true
    defer: true
runcmd:
 - [set, -x]
 - [mkdir, /root/ws]
 - [python3, -m, venv, /root/.venv]
 - [., /root/.venv/bin/activate]
 - [pip3, install, rosdep]
{% if pro_token %}
 - [pip3, install , vcstool]
 - [mkdir, -p, /root/ws_underlay/src]
 {% endif %}
