## template: jinja
#cloud-config

apt:
  sources:
    ros2:
      source: "deb [arch={{ v1.machine }}] http://repo.ros2.org/ubuntu/main {{ v1.distro_release }} main"
      keyid: C1CF 6E31 E6BA DE88 68B1 72B4 F42E D6FB AB17 C654
package_update: true
package_upgrade: true

packages:
  - build-essential
  - cmake
  - curl
  - git
  - lsb-release
  - python3
  - python3-pip
  - software-properties-common
  - python3-colcon-common-extensions
  - python3-rosdep
  - python3-setuptools
  - python3-vcstool
  - ros-{{ v1.ros_release }}-ros-base
  - ros-dev-tools

